name: Release # Or Release Resume PDF, whichever you prefer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Add this block
      contents: write # Grant write permissions to contents (releases, assets)

    steps:
      - uses: actions/checkout@v3

      - name: tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token now has proper permissions

      - name: Upload resume.pdf
        uses: actions/upload-release-asset@v1.2.1 # Still recommend updating this from v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: resume.pdf
          asset_name: ${{ github.actor }}_resume.pdf
          asset_content_type: application/pdf